### ISSUE TITLE
Ability to skip running npm install

### ISSUE THREAD

**Issue by michael-pomelo** [EPMatt/reviewdog-action-tsc#43]
I am trying to run this in my repo but I keep running into issues with the `npm install` part of the script. Because of some other issues, I need to run `npm install` with the `--legacy-peer-deps` argument or else it will fail.  Since this action only runs `npm install` with no way to override the args passed to npm, my install fails.

But I am confused why it is even trying to run npm install in the first place.  I have `npm ci` as a previous step in my build--so all deps (inlcuding tsc) would be installed.  I then tried to make a separate step that installed tsc globally, but that also did not work--this script still tried to run `npm install`.  

There needs to be an option to either pass args to npm, use `npm ci` install of `npm isntall`, or do better checking if `tsc` is actually installed.

**Comment by EPMatt** [comment]
Hi @michael-pomelo,

thank you for reporting here. The `npm install` step should only run when `tsc` is not installed in the provided `workdir`. Here's the action's code section in charge of checking the presence of `tsc`:

https://github.com/EPMatt/reviewdog-action-tsc/blob/9fc7bbc1cb021a9e6d4e09d03e0e5a1b7c742b90/script.sh#L14-L18

Therefore, if `npm ci` at the previous step in your job runs successfully, `tsc` should already be installed; the action should detect it and skip `npm install`.

Could you please share the YAML for the workflow you're trying to setup with this action?
Thanks!

**Comment by michael-pomelo** [comment]
Truncated, but you get the point:

```name: Javascript Code Format
on: [pull_request]
jobs:
  lint:
    name: JS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 1
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            continue:
              - '**/*.ts'
              - '**/*.tsx'
              - '**/*.js'
              - '**/*.jsx'
              - '**/*.scss'
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
        if: steps.changes.outputs.continue == 'true'
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        if: steps.changes.outputs.continue == 'true'
      - name: Install TS Compiler
        run: npm i -g tsc --legacy-peer-deps
        if: steps.changes.outputs.continue == 'true'
      - name: Install dependencies
        run:  npm ci
        if: (steps.cache-node-modules.outputs.cache-hit != 'true' && steps.changes.outputs.continue == 'true')
      - name: Prettier
        run: npx prettier ./ --check --config .prettierrc
        if: steps.changes.outputs.continue == 'true'
      - name: ESLint
        run: npm run lint:js
        if: steps.changes.outputs.continue == 'true'
      - name: Stylelint
        run: npm run lint:style
        if: steps.changes.outputs.continue == 'true'
      - uses: EPMatt/reviewdog-action-tsc@v1
        with:
          workdir: ./apps/web
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
        if: steps.changes.outputs.continue == 'true'
```

All the other steps run fine. You'll see I even added a global install to tsc but to no avail. This is not a new yml either, so I know everything works and npm deps get installed as normal. And yes, `tsc` is listed as a dep in my `package.json`

**Comment by EPMatt** [comment]
Hi @michael-pomelo,
thank you for your feedback.

Where is your `package.json` file located? From your job definition I can see that you're running `npm ci` on the repo's root folder, while the action is configured to run on the `./apps/web` subfolder. What happens is that the action looks for `tsc` in `./apps/web/$(npm bin)`, and since it cannot be found it runs `npm install` in the `./apps/web` subfolder, failing because I guess no `package.json` resides there.

Please try to run the action with the `workdir` set to `.`, allowing it to properly recognize `tsc` being installed; you can then configure `tsc` to only run on the `./apps/web` subfolder by passing the appropriate flags via the `tsc_flags` option.

Let me know if this solves your issue.
Thanks! :)

**Comment by michael-pomelo** [comment]
Thank you, that worked.  The reason is because we run a monorepo, so all deps are only installed at the root but every project (in this case, `apps/web`) have its own `package.json` file.

IMO it should be made more clear that the action checks for `tsc` to be installed in the `workdir`. I'd be more than happy to open a PR if you wish.

Appreciate the help!

**Comment by EPMatt** [comment]
Hi @michael-pomelo,

I'm glad that your issue is solved. :)
> IMO it should be made more clear that the action checks for tsc to be installed in the workdir. 

I agree with you, even if that information is included in the examples and in the input documentation, maybe that information needs to be more visible. I'd consider adding an entry to readme's FAQs section.

> I'd be more than happy to open a PR if you wish.

Sure, I'd be happy to receive your contribution. :) 

Thank you so much for your help!

**Comment by EPMatt** [comment]
Hi @michael-pomelo,

You can find a reference also in the input documentation:

https://github.com/EPMatt/reviewdog-action-tsc/blob/b1e14379ba764724b38552d30621891cd2473c26/README.md?plain=1#L29-L34

>  I did not take that to mean "there needs to be a node_modules directory in the subfolder that has a tsc executable installed in subfolder/node_modules/.bin`. Those are very different.

I agree on this, but I don't think we should state that `tsc` needs to be installed in the `node_modules/.bin` directory, as this relates to how npm install modules and might confuse users not experienced with node modules installation and resolution.

I'd prefer to make it clear in the docs that the action runs `npm install` if `tsc` was not detected as installed as a module, in the provided `workdir`. If `npm install` cannot be run due to the project setup, users should take care of installing the `tsc` module by running the appropriate installation command (as you correctly did in your workflow), according to their setup and specific needs.

We could also consider adding an additional input, pointing to the `tsc` installation location. Although this might allow for better customization, I'm afraid that we're diving into a too specific use case, and I'd also prefer to keep the action's interface as similar as possible to the one from other reviewdog actions (such as the [eslint action](https://github.com/reviewdog/action-eslint), which provides the same exact functionality, but for `eslint`).

Please let me know what are your thoughts about this.
Thanks!
